---
title: "Get started with rmangal"
author:
  - name: Steve Vissault
  - name: Kevin Cazeles
bibliography:
  - ../inst/bib/get_started.bib
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(magrittr)
library(USAboundaries)
library(mapview)
library(igraph)
library(sf)
library(rmangal)
```


## Context

<!-- the ecography paper paper should help here -->
rmangal is a R client for MANGAL API. MANGAL is a collection of 172
datasets representing over 1300 published ecological networks.
[](http://www.mangal.io/about/). In 2016, a first paper was published with the
first release of rmangal [@poisot_mangal_2016]. Since then, the API has been
re-written and several ecological networks have been added.

<!-- A word about few words about the future of mangal -->

<!-- A word the absence of token -->


## Data available

<!-- add a diagram that describes the data base-->
<!-- it should be clear the difference between a dataset and a network -->


## How to use rmangal

`rmangal` includes 5 search functions to quickly identify relevant data sets
or relevant ecological network available in the data base:

- `search_datasets()`: identify data sets using keyword such as name, year;
- `search_interactions()`:identify relevant datas ets nased on interactions kind;
- `search_networks()`: identify networks based on a keyword or a geographical area;
- `search_reference()`: search based on the `doi` of the publication associated with;
- `search_taxa()`: identify data sets that included a given taxonomic entity.

All these functions return specific objects containing the information needed
to retrieve the set of corresponding ecological networks with
`get_collection()`.

```r
networks <- search_*() %>% get_collection()
```

If there is only one network to be retrieved, `get_collection()` returns a `mgNetwork` object, otherwise it returns a object of class  `mgNetworksCollection` which is a collection (a list) of `mgNetwork` objects.


```r
ref <- get_collection(networks)
```

Below, we illustrate this in more details.


## Search functions

### Finding specific data sets

All data sets pertaining to lagoon:

```{R}
lagoon <- search_datasets(query = 'lagoon')
class(lagoon)
dim(lagoon)
```

All data sets published in 2011

```{R}
df2011 <- search_datasets(query = '2011')
dim(df2011)
```

Moreover, `search_datasets()` allows the user to retrieve all data sets:

```{R}
all_datasets <- search_datasets()
head(all_datasets[, c("id", "name" ,"description")])
```



### Retrieve a specific set of networks

Once data sets identified, you can retrieve the ecological networks included:

```{R}
net_lagoons <- get_collection(lagoon)
```

Alternatively, you can use `search_networks()`


```{R}
all_networks <- search_networks()
netw18 <- get_network_by_id(18)
## 2B fixed
collec <- search_networks(query="insect%") %>% get_collection()
collec[[1]]
```


### Mapping networks

<!-- of course map are fun but I woud put that in a sperate vignette -->

```{R}
all_networks <- search_networks()
mapview(all_networks, legend = FALSE)
```







## How to convert network to igraph object?

```{R}
ig_lagoons <- as.igraph(net_lagoons)
plot(ig_lagoons[[1]], vertex.label = vertex_attr(ig_lagoons[[1]],"original_name"))
```




## Search over taxonomic name, retrieve networks which include this taxa

```{R}
sr_ficus <- search_taxa("Ficus")
# Plot the location
mapview(sr_ficus$networks, legend = FALSE)
# Get networks
net_ficus <- get_collection(sr_ficus)
net_ficus[[1]]
```

## Search by location, used buffer, polygons to retrieve networks.

```{R}
area <- us_states(state = "california")
networks_in_area <- search_networks(area)
mapview(networks_in_area, legend = FALSE)
```

## How to use the ids (bold, tsn, ncbi etc.) to get extra taxonomic informations using taxize?

```{R}
resTsn <- search_taxa(tsn = 28749)
resNcbi <- search_taxa(ncbi = 47966)
resEol <- search_taxa(eol =  583069)
resBold <- search_taxa(bold = 100987)
```

## Retrieve references for a specific dataset

```{R}
ref <- get_citation(get_network_by_id(18))
cat(gsub('\\},', "\\},\n", ref), "\n")

ref2 <- search_networks("lagoon") %>% get_collection %>% get_citation

```

## References
